services:
  book_catalog:
    build: ./book_catalog
    ports:
      - "5000:5000"
    depends_on:
      - db
  inventory_management:
    build: ./inventory_management
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
